# external signal generator
#set_property PACKAGE_PIN P15 [get_ports clk]
# Nexys 4 crystal oscillator
set_property PACKAGE_PIN E3 [get_ports clk]
set_property PACKAGE_PIN F14 [get_ports miso]
set_property PACKAGE_PIN D17 [get_ports mosi_out]
set_property PACKAGE_PIN C12 [get_ports reset]
set_property PACKAGE_PIN B13 [get_ports spi_clk_out]
set_property PACKAGE_PIN E17 [get_ports spi_en_out]
set_property PACKAGE_PIN G3 [get_ports {gpio_input[0]}]
set_property PACKAGE_PIN G1 [get_ports {gpio_input[1]}]
set_property PACKAGE_PIN H1 [get_ports {gpio_input[2]}]
set_property PACKAGE_PIN H4 [get_ports {gpio_input[3]}]
set_property PACKAGE_PIN F3 [get_ports {gpio_input[4]}]
set_property PACKAGE_PIN G2 [get_ports {gpio_input[5]}]
set_property PACKAGE_PIN G4 [get_ports {gpio_input[6]}]
set_property PACKAGE_PIN H2 [get_ports {gpio_input[7]}]
set_property PACKAGE_PIN J4 [get_ports {gpio_input[8]}]
set_property PACKAGE_PIN J3 [get_ports {gpio_input[9]}]
set_property PACKAGE_PIN E7 [get_ports {gpio_input[10]}]
set_property PACKAGE_PIN K2 [get_ports {gpio_input[11]}]
set_property PACKAGE_PIN G6 [get_ports {gpio_input[12]}]
set_property PACKAGE_PIN J2 [get_ports {gpio_input[13]}]
set_property PACKAGE_PIN E6 [get_ports {gpio_input[14]}]
set_property PACKAGE_PIN K1 [get_ports {gpio_input[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports miso]
set_property IOSTANDARD LVCMOS33 [get_ports mosi_out]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports spi_clk_out]
set_property IOSTANDARD LVCMOS33 [get_ports spi_en_out]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_input[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_input[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_input[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_input[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_input[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_input[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_input[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_input[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_input[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_input[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_input[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_input[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_input[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_input[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_input[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {gpio_input[15]}]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]




